name: Create New Project Veena Log

on:
  workflow_dispatch:

jobs:
  new-log:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Get latest day number
        id: get_day
        run: |
          latest=$(ls | grep '^day-[0-9]\+\.md$' | sed 's/day-\([0-9]\+\).md/\1/' | sort -n | tail -1)
          if [ -z "$latest" ]; then
            next=1
          else
            next=$((latest + 1))
          fi
          echo "day_num=$next" >> $GITHUB_ENV

      - name: Create new ritual file
        env:
          DAY_NUM: ${{ env.day_num }}
        run: |
          FILE="day-$DAY_NUM.md"
          echo "# Project Veena – Day $DAY_NUM" > "$FILE"
          echo "" >> "$FILE"
          echo "**Date:** $(date +%Y-%m-%d)" >> "$FILE"
          echo "**Start Time:**" >> "$FILE"
          echo "**Focus of the Session:**" >> "$FILE"
          echo "**What I Did:**" >> "$FILE"
          echo "**Mood (Before → After):**" >> "$FILE"
          echo "**Distractions / Resistance:**" >> "$FILE"
          echo "**One Line Summary:**" >> "$FILE"

      - name: Commit and push new log
        env:
          DAY
